id: DCA5F2428
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-12-31T06:57:30+00:00'
last_modified: '2022-05-27T09:48:56.850322+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    '2358':
      image_group_id: I1PD95905
      title: དབུ་མ་ཤེས་རབ་ལ་འཇུག་པ།
      total_pages: 1913
      order: 60
      base_file: 2358.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
